export default {
  API_STRIPE_TEST:
    'pk_test_51HPrCBAovamKBaC1fH8Lau08e554LGOfjCF72kAJT9DUHpQqUUZ5LWnxiXTFNQkhYZzAgyB6gzDbWGXs8sQRmpkI00S0vZ1D3O',

  PLAN_TEST_BASIC_PRODUCT_ID: 'prod_I3q8dVmru5Nm8u',
  PLAN_TEST_BASIC_PRICE_ID: 'price_1HTiRsAovamKBaC1840JyApY',
  PLAN_TEST_CONTROL_PRODUCT_ID: 'prod_I45qf3JAQg7Dgv',
  PLAN_TEST_CONTROL_PRICE_ID: 'price_1HTxelAovamKBaC1k27Yxw5C',
  PLAN_TEST_ADVANCED_PRODUCT_ID: 'prod_I45sHdJ1IhmDYA',
  PLAN_TEST_ADVANCED_PRICE_ID: 'price_1HTxgeAovamKBaC1v0uqDiLT',

  PLAN_BASIC_PRODUCT_ID: 'prod_I3q80WnG3lxwcE',
  PLAN_BASIC_PRICE_ID: 'price_1HTiS2AovamKBaC16BOlZ4uI',
  PLAN_CONTROL_PRODUCT_ID: 'prod_I3q9Xq28vrh0DZ',
  PLAN_CONTROL_PRICE_ID: 'price_1HTiSqAovamKBaC1gNh1sv1V',
  PLAN_ADVANCED_PRODUCT_ID: 'prod_I3q97MsnEbj1dk',
  PLAN_ADVANCED_PRICE_ID: 'price_1HTiTNAovamKBaC104OtjzbV',

  PERSON_TYPE_CLIENT: 'Cliente',
  PERSON_TYPE_SUPPLIER: 'Fornecedor',

  FILTER_ALL: 'ALL',
  FILTER_ACTIVE: 'ACTIVE',
  FILTER_INACTIVE: 'INACTIVE',

  PF: 'Pessoa Física',
  PJ: 'Pessoa Jurídica',
  PF_TYPE: 'PF',
  PJ_TYPE: 'PJ',

  IND_INSCR_SOCIAL_Y: 'Y',
  IND_INSCR_SOCIAL_N: 'N',
  IND_INSCR_SOCIAL_I: 'I',
  IND_INSCR_SOCIAL_Y_LABEL: 'Contribuinte',
  IND_INSCR_SOCIAL_N_LABEL: 'Não contribuinte',
  IND_INSCR_SOCIAL_I_LABEL: 'Contribuinte isento',

  DEFAULT_ORDER: 'name',
  DEFAULT_HEADERS: [{ field: 'name', displayName: 'Nome' }]
}
